name: Playwright CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v3

      - name: Start Containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm i

      - name: Setup database and complete joomla installation
        run: node installJoomla.js
      
      - name: Navigate to test folder and install dependencies
        run: cd e2e && npm i

      - name: run tests 
        run: npm run test:acceptance features/

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
